version: '3.8'
services:
  expo-app:
    build:
      context: ./docexpoapp
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./docexpoapp:/app
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - EXPO_PACKAGER_HOSTNAME=192.168.0.124
    stdin_open: true
    tty: true
