version: '3.8'
services:
  nextjs-app:
    build:
      context: ./nextproject
    ports:
      - '3000:3000'
    volumes:
      - ./nextproject:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
